### ISSUE TITLE
Can't get custom action buttons working

### ISSUE THREAD

**Issue by pordonez** [rubanraj54/vue-bootstrap4-table#14]
Hi, 

Delighted with the table.  Thank you.

I'm not able to get the custom action buttons working/visible.  All else works as expected.

I'm using the [Basic Usage](https://rubanraj54.gitbook.io/vue-bootstrap4-table/usage) sample with the [custom action buttons](https://rubanraj54.gitbook.io/vue-bootstrap4-table/custom-action-buttons) sample.

Any help would be greatly appreciated.  Thanks again, Peter

**Comment by rubanraj54** [comment]
Hi @pordonez 

Could you please make an example in codepen/fiddle to check your code?
else you can post your sample code here, I'll have a look at.

Cheers,
Ruby.

**Comment by pordonez** [comment]
Hi Ruby,  I've posted my App.vue and main.js files [here](https://gist.github.com/pordonez/1faa75a0eb7c5031db2c22bdae25ca26). 

Thanks, Peter

**Comment by rubanraj54** [comment]
Hi @pordonez 

Sorry, in the document I missed passing actions to vue-bootstrap4-table. I updated the document & you can use the following example.

```vue
        <vue-bootstrap4-table :rows="rows" 
                                :columns="columns" 
                                :config="config"
                                :actions="actions"
                                @on-download="onDownload">
        </vue-bootstrap4-table>
```

Cheers,
Ruby.

**Comment by pordonez** [comment]
Thank you Ruby.  This works.  You truly are a gem.

**Comment by rubanraj54** [comment]
> Thank you Ruby. This works. You truly are a gem.

Thanks for your comment. If you would like to support this plugin development, please give this repository a star. :+1:
