### ISSUE TITLE
Pagination : Preserve current index 

### ISSUE THREAD

**Issue by abdulkhaderp** [rubanraj54/vue-bootstrap4-table#16]
This is not really an issue, but a help /feature request . My customer want to preserve the current pagination index while he refresh the data . For example, if the user is at page 4, and he refresh the table data ( i assign new server response to this.rows) , he want to be at page 4 itself with updated data. Any luck ?

**Comment by rubanraj54** [comment]
Hi @abdulkhaderp 

Thanks for pointing out this. Right now there is no way to preserve the current pagination index.

But it is a valid feature request. I will consider this request & probably make a configurable option to let the user choose whether to preserve the current index or not if there is a data change.

I will implement this feature in the upcoming release (most probably this weekend).

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @abdulkhaderp,

I implemented this feature in today's release. So please update the package and try it out.

To enable preserving pagination index, you should set "preservePageOnDataChange: true" in the config.
By default, it is set to false.

Cheers,
Ruby.

**Comment by abdulkhaderp** [comment]
Thanks @rubanraj54 . I will try it out.

**Comment by rubanraj54** [comment]
Great.. if you would like to support this plugin, please star this repository.. 😀

**Comment by shahabazdev** [comment]
Hi,

Any possibility to retain this if the user goes forward to a detail page from a table row, and then back to the table? As localstorage variable perhaps?
