### ISSUE TITLE
Card title div

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [rubanraj54/vue-bootstrap4-table#17]
Would we be able to get a slot or some way to effect the title div on the card as currently it is hard coded to be centred and currently i need it to be left aligned and I would like the ability to add extra things to that title div, e.g. extra buttons.

Now i have got around this for now by turning off card mode and doing the card part myself but it would be great to have this all built in :-)

**Comment by rubanraj54** [comment]
Hi @Chris-Pratt-Clystnet 

Thanks for letting me know. I will consider your request. :-)

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @Chris-Pratt-Clystnet 

I released a new version today which includes this feature.

Now you can override card header & footer using slots. 

Example:
```vue
<template slot="card-header">
    your content goes here
</template> 

<template slot="card-footer">
    your content goes here
</template>
```

I will close this issue now.

Cheers,
Ruby.
