### ISSUE TITLE
Keeping the current index when queryparams have been changed

### ISSUE THREAD

**Issue by sdrig** [rubanraj54/vue-bootstrap4-table#18]
Hi, 
I would like to thank for this amazing grid. I've been trying to solve one of my requirements that says when the current queryparams changed the page index has to be changed to 0 (zero). 

repro : 
1- call fetchdata when component mounted. 
2- change page index to 2 
3- enter some value into the global search.(considering that server will response only one page)
4- grid does not show any result due to page index current value is still 2

**Comment by rubanraj54** [comment]
Hi @sdrig 

Thanks for letting me know this issue. I will try to reproduce this issue and fix it in my next release (probably this weekend).

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @sdrig 

I couldn't be able to reproduce this issue. 

In the current version, if there is a change in queryParams it triggers an event and the user can fetch new data and assign it to the table. So now the table will move the index automatically to the initial position (zero). 

If you can make a fiddle/codepen, it would be easy for me to debug more in-depth.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @sdrig ,

I implemented a few features in today's release which includes preserving the page index. So please update the package and try it out.

To enable preserving pagination index, you should set preservePageOnDataChange: true in the config.
By default, it is set to false.

In your case, I guess it will work out of the box. Whenever query changes, then the page index will become 0 (first page). 

Cheers,
Ruby.

**Comment by sdrig** [comment]
It's working like a charm! Thanks

**Comment by rubanraj54** [comment]
Hi @sdrig , 

Good to see that it works. 

If you would like to support this plugin, please star this repository :-)
