### ISSUE TITLE
Column multi filter options from an array variable 

### ISSUE THREAD

**Issue by daoudzd** [rubanraj54/vue-bootstrap4-table#19]
hi 
i can't use an array of items for column filter options,
for example:
**array variable** 
![image](https://user-images.githubusercontent.com/13900466/54037868-134aca80-41b7-11e9-91c0-5c1c33cb84f2.png)

**column**
![image](https://user-images.githubusercontent.com/13900466/54037697-b18a6080-41b6-11e9-922b-0b23f12b8b54.png)

**result**
![image](https://user-images.githubusercontent.com/13900466/54038491-97ea1880-41b8-11e9-8a14-2f21c2fa7691.png)

thank you.

**Comment by rubanraj54** [comment]
Hi @daoudzd ,

can you please post all your list items?

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @daoudzd ,

I see the problem now. You're referencing a data property to another data property. But this doesn't work in vue. Reference : https://stackoverflow.com/a/46491490/2708249

What you can possibily do is, let keep the options as empty array and assign the options in the mounted function.

For example, let say you have your options in `Listes` data variable and assign empty array to your options field in column config `options : []` .

And in the mounted function assign the `Listes` values to the `options` field in the column config.

```vue
mounted() {
    let yourColumnIndex = 0;
    this.columns[yourColumnIndex].filter.options = this.Listes;
},
```

Hope this solves your problem.

Cheers,
Ruby.

**Comment by daoudzd** [comment]
hello @rubanraj54 ,
thank you its working as you described 👍 

![image](https://user-images.githubusercontent.com/13900466/54111558-0eb32b80-43dc-11e9-94c8-04e291a73a10.png)

**Comment by rubanraj54** [comment]
Great, I am closing this issue now.

**Comment by bureauvk** [comment]
I am using the same setup, only the column isn't showing any results if I use this code:
```
{
 label: "Tags",
 name: "tags",
 filter: {
  type: "select",
  placeholder: "Search tags",
  mode: "multi",
  options: []
 },
 slot_name: "tags_field"
},
```

When I use this:
`name: "tags[0].id",`
The filtering is only working for the first object in the array. 

Is it possible to filter on all the objects?
