### ISSUE TITLE
row_classes align-middle not working

### ISSUE THREAD

**Issue by pordonez** [rubanraj54/vue-bootstrap4-table#22]
Hi,

Apologies if this is a dup of issue #15.

I've included an icon in a table data that I'm trying to middle align.  I've added the following to my columns array but it's not working:
        {
          name: "check",
          row_classes: "align-middle"
        },

My understanding is that "align-middle" should be added to the corresponding td, but that doesn't appear to be happening.  If I manually align middle in DevTools I get the desired behavior (see screencap). 
<img width="615" alt="Screen Shot 2019-03-12 at 1 31 48 PM" src="https://user-images.githubusercontent.com/235676/54222289-75fbd900-44cb-11e9-8651-ce48da6f60f4.png">

Any help would be greatly appreciated.  Thanks, Peter

**Comment by rubanraj54** [comment]
Hi @pordonez 

Thanks for letting me know this. 

I was wondering why it is not working and found that in previous release I commented out few lines of code for testing and forgot to uncomment them.

I fixed this in new release 1.0.29. So could you please update your package to get this working.

Also, if you would like to use advance overriding classes for row, columns, cells, etc,, please checkout the examples here https://rubanraj54.gitbook.io/vue-bootstrap4-table/custom-classes.

Cheers,
Ruby.
