### ISSUE TITLE
Single and Multi Filter Click Not Functioning

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [rubanraj54/vue-bootstrap4-table#23]
I am not quite sure when this started happening but it must of been with one of the latest releases but now when ever i click on a item in a single/multi select filter then nothing happens.

I have checked and Vue is emitting the on-select-option event but i'm guessing something is going wrong after that and the on-change-query event is not being emitted.

**Comment by rubanraj54** [comment]
Hi @Chris-Pratt-Clystnet 

That's right, this issues was caused because of the new feature "initializing filters before table rendering".

Thanks Chris for letting me know that. I fixed it and available in new version 1.1.1

Cheers,
Ruby.
