### ISSUE TITLE
action button ccs

### ISSUE THREAD

**Issue by daoudzd** [rubanraj54/vue-bootstrap4-table#25]
hi, is there any way to change actions button css classes, if not can you provide an option to change class="btn btn-primary" to something else?

**Comment by rubanraj54** [comment]
Hi @daoudzd 

Currently there is no way, but I can add this feature in my next release.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hey @daoudzd 

This feature is rolled out in new release 1.1.2. Note that, still this is not yet documented in Readme.

Example:

```javascript
actions: [
    {
        btn_text: '<span>Download <i class="fas fa-download"></i></span>',
        class: "btn btn-primary my-custom-class",
        event_name: "on-download",
        event_payload: {
            msg: "my custom msg"
        }
    }
]
```

Cheers,
Ruby.

**Comment by daoudzd** [comment]
thank you

**Comment by daoudzd** [comment]
i tested it in [https://codepen.io/rubanraj54/pen/zyZdzN ](url) and found that ` class: "btn btn-primary"`  is working but  

but `btn_text: '<span>Download <i class="fas fa-download"></i></span>',` is not working

**Comment by daoudzd** [comment]
and noticed that buttons ccs in filter changed from 
![image](https://user-images.githubusercontent.com/13900466/54424119-1e977c00-470a-11e9-8222-e1b2eab5e851.png)

to 

![image](https://user-images.githubusercontent.com/13900466/54424136-2a833e00-470a-11e9-8d02-fc5ea21fca48.png)

**Comment by rubanraj54** [comment]
> i tested it in [https://codepen.io/rubanraj54/pen/zyZdzN ](url) and found that ` class: "btn btn-primary"` is working but
> 
> but `btn_text: '<span>Download <i class="fas fa-download"></i></span>',` is not working

Hi @daoudzd ,

I didn't updated new version in the codepen. That's why it wasn't working there.

I made a codepen example here https://codepen.io/rubanraj54/pen/Oqvgwj .

And note that, if you want to show the icon you should include some icon packages in your project.
In my example I used fontawesome css package to show download icon.

**Comment by rubanraj54** [comment]
> and noticed that buttons ccs in filter changed from
> ![image](https://user-images.githubusercontent.com/13900466/54424119-1e977c00-470a-11e9-8222-e1b2eab5e851.png)
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/13900466/54424136-2a833e00-470a-11e9-8d02-fc5ea21fca48.png)

you can take a look at this issue #12 for more details why I change the design. Also now it is configurable to enable or disable clear buttons in global search and simple filter, and also you can override the clear button icon for your choice.
