### ISSUE TITLE
global search class

### ISSUE THREAD

**Issue by pordonez** [rubanraj54/vue-bootstrap4-table#26]
Hi,

I'd like to add classes to the global search to, for example, increase the margin.  Is that possible?

Thanks, Peter

**Comment by rubanraj54** [comment]
Hey @pordonez 

Currently, it is not possible, But I will consider this feature in my next release.

Cheers,
Ruby.

**Comment by pordonez** [comment]
Thank you Ruby.  I added a margin to the action button and I'd like to do the same for the search field for a consistent look.  Thanks again, Peter

**Comment by rubanraj54** [comment]
Hi @pordonez 

Now you can add class to global search.

```javascript
global_search: {
    placeholder: "Enter custom Search text",
    visibility: true,
    case_sensitive: false, // default false
    showClearButton: true,
    class: "my-global-search-class my-global-search-class-two"
},
```

Please upgrade your package to get this feature.

Cheers,
Ruby.
