### ISSUE TITLE
Could I remove the card style?

### ISSUE THREAD

**Issue by LarkLib** [rubanraj54/vue-bootstrap4-table#3]
I don't need  card_title and pagination_info but still has a box with header around the table.
How to remove the box to only keep the table?
table around a card:
|------------------------------|
|------------------------------|
|      |--------------------|　　　|
|      |    table          　　　　      　|　　　|
|      |--------------------| 　　　|
|------------------------------|

**Comment by rubanraj54** [comment]
Hi @LarkLib ,

Thanks for made an issue.

Can you please update your package to new version (1.0.15 or above)?

Fixes:

* Users can switch between card style layout with table and default plain table layout.

You can enable or disable it by setting `**card_mode**` to true/false in the table config.

### Example
```javascript
...
data: function () {
    return {
        rows: [],
        columns: [],
        config: {
            ...
            card_mode: false
            ...
        }
    }
}
...
```

If you still like to render table inside card body, you can render vue-bootstrap4-table by urself and customize based on your wish.
💖

**Comment by LarkLib** [comment]
Thanks for your quickly work, it is working well now, a star!
