### ISSUE TITLE
12. Custom action buttons

### ISSUE THREAD

**Issue by grafxflow** [rubanraj54/vue-bootstrap4-table#30]
Is it possible to add font awesome icons to custom actions? plus choose wether to place them above or below the table layout?

**12. Custom action buttons**

```
<template slot="custom-action-export">
<font-awesome-icon :icon="['fas', 'sort']" fixed-width />
</template>
```

P.S. This is a really great vue js component :)

**Comment by grafxflow** [comment]
For now I have added them separately on the vue page.

**Comment by rubanraj54** [comment]
Hi @grafxflow 

Thanks for your suggestion. Right now there is no option to add a slot for action buttons. However I will consider this request and implement it in future release.

Now you can add icon or icon with text via "btn_text" attribute in action button. To achieve this, i recommend you to load font awesome icons package via CDN.

1. Load fontawesome in your html `<head>`
```html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
 ```
Now you can add icon via "btn_text" as shown in the below example.

```javascipt
actions: [
    {
        btn_text: '<span>Export <i class="fas fa-sort"></i></span>',
        class: "btn btn-primary my-custom-class",
        event_name: "on-download",
        event_payload: {
            msg: "my custom msg"
        }
    }
]
```

I hope this will solve your problem temporarily. I will let you know after I add the slot feature for action buttons.

Cheers,
Ruby.

**Comment by grafxflow** [comment]
Okay thanks for that, the only issue is that I am loading only the font-awesome icons I am using in order to keep the app.js file size down. 

Is there any other way to return html as maybe a method?

**Comment by rubanraj54** [comment]
Hi @grafxflow ,

I found a workaround for this issue and fixed it in the develop branch (you can verify the commit above). Now you can achieve what you requested for. 

**Action config**
```javascript
actions: [
    {
        btn_text_slot_name : "custom-action-export",
        class: "btn btn-primary my-custom-class",
        event_name: "on-export"
    }
]
```
**Slot Usage**

```vue
<template slot="custom-action-export">
     <font-awesome-icon :icon="['fas', 'sort']" fixed-width />
</template>
```

This is still in the develop branch, and releasing a new version on this Friday. So you can use this feature from next version.

Cheers,
Ruby.

**Comment by grafxflow** [comment]
So if I understand it correctly I could target a column in the table and place this and other buttons inside?

**Comment by rubanraj54** [comment]
The new commit fixes the actual issue #30 "slot for custom action button icons(Vue component icon)".

The Buttons inside a separate column is already possible. I made a new codepen for you https://codepen.io/rubanraj54/pen/ywRdMB. 

![Screenshot from 2019-03-21 09-53-45](https://user-images.githubusercontent.com/10024405/54741606-46ca2380-4bbf-11e9-8716-aa003ffac616.png)

I hope this codepen will help you.

Cheers,
Ruby.

**Comment by grafxflow** [comment]
Thanks Ruby. 

That's perfect 👍

**Comment by rubanraj54** [comment]
Hi @grafxflow 

Adding "Font awesome icon" vue components icon for custom action buttons is now available in new version. Please upgrade your package.

Cheers,
Ruby.

**Comment by grafxflow** [comment]
Perfect :)
