### ISSUE TITLE
2 or more instances of tables on the same vue page?

### ISSUE THREAD

**Issue by grafxflow** [rubanraj54/vue-bootstrap4-table#31]
Is it possible to have 2 or more table instances on the same vue page?

**Comment by rubanraj54** [comment]
Why not? It is possible. 

But keep in mind that, You should have different config, rows and columns data for each table if all the tables look different.

If all table looks same, but only the data is different, you can reuse the config and columns data. (But I always use different config & columns data for different tables eventhough all tables looks same - for easier debugging).

https://codepen.io/rubanraj54/pen/KErNrG

Cheers,
Ruby.

**Comment by grafxflow** [comment]
Perfect works a charm. 👍
