### ISSUE TITLE
Clearing selected rows 

### ISSUE THREAD

**Issue by ojas360** [rubanraj54/vue-bootstrap4-table#37]
When i selected a row from the checkbox table and perform some action on the rows.
The rows get unselected but the header checkbox remains checked.
How do i unselect the rows explicitly from any method?

Example:
![image](https://user-images.githubusercontent.com/7880879/55533845-3a21f100-56d0-11e9-9ae8-4cb55e6cd9bd.png)
Here the rows 1 and 2 also selected but they are not showing.
Actually they should be unselected from the header checkbox too.

**Comment by rubanraj54** [comment]
Hi @ojas360 

Sorry, I couldn't understand the problem.
Could you please give me more information or a codepen example would be more easy to debug.

**Comment by rubanraj54** [comment]
Hi @ojas360 

currently What version are you using?

**Comment by ojas360** [comment]
I am using version 1.1.2.
The process i am following is: 

On select of rows, i m inserting rows into another array.
On some processing on that data after success i am modifying the rows of the datatable by using map()
When i modify the rows, the rows get deselected on the UI, But they are actually selected (as shown in the image attached).

**Comment by ojas360** [comment]
Currently made it working by assigning ref to the table and then

this.$refs.refname.unSelectAllItems();

**Comment by Mominsami07** [comment]
> Currently made it working by assigning ref to the table and then
> 
> this.$refs.refname.unSelectAllItems();

hey ojas360,
Can you show me how you made it ? 
I mean this function unSelectAllItems(), is built in, or you made it . 
Thanks in advance.

**Comment by Mominsami07** [comment]
> Currently made it working by assigning ref to the table and then
> 
> this.$refs.refname.unSelectAllItems();

You saved me Man,
Thanks a lot ☺
