### ISSUE TITLE
Get Selection

### ISSUE THREAD

**Issue by soongsta** [rubanraj54/vue-bootstrap4-table#38]
Hi There

Is there a way to access the selected rows in (for example) the onDownload

 onDownload(payload) {
      //process selected items
      console.log(payload.items)
    }

Or do we track the selected items through a local array?

**Comment by rubanraj54** [comment]
HI @soongsta 

Currently, it doesn't support sending selected items in the payload.

But it is a valid request, so I will consider implementing this in my next release.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @soongsta 

Now you can get the "selectedItems" array along with the action buttons event payload.

```javascript
onDownload(payload) {
//process selected items
console.log(payload.selectedItems)
}
```

There is another way to access the selected row's data directly (Note: But this is not a right approach, still in this case you can use it)

**Example:** 

Set a `ref` name to the table component. 

```vue
<div id="app">
  <vue-bootstrap4-table ref="myvuetable" :rows="rows" :columns="columns" :actions="actions" :config="config" @on-download="onDownload" >
  </vue-bootstrap4-table>
</div>

```

And in your code, you can access the selected_items directly as shown below.

```vue
this.$refs.myvuetable.selected_items
```

Cheers,
Ruby.
