### ISSUE TITLE
Row value empties after sort if it contains reference to element of array

### ISSUE THREAD

**Issue by nullday** [rubanraj54/vue-bootstrap4-table#40]
Each row in my dataset has a key `items` that contains array of objects and each object has key `title`.

Example:
```
[{ 
items: [
  { 
    title: 'abc'
  }
]
}]
```

I have a column called `title` with name that contains reference to element of array (`name: 'items[0].title'`).
It works fine, the table renders the value. 
But when you sort on any column, all the values in that title column disappear, just an empty string.

If you remove array from the name (just `name: 'title'`), then the column has empty value when table is rendered. But when you sort on any column, value appears.

So it looks like value being copied in internal row structure as `title` and then some reference breaks and doesn't count `items[0]` prefix.

**Comment by rubanraj54** [comment]
Hi @nullday 

It is really strange. Please give me some time.

I will have a look into this and fix this issue.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @nullday 

I've tried a scenario as you said, but it is working perfectly. You can check in this codepen example https://codepen.io/rubanraj54/pen/oOWwBb

Table can able to render the values in the column and the values are not disappering from "Title" column after any column sorting. If you still have problem, please make a codepen example for me. It would be easier for me to debug.

Cheers,
Ruby.

**Comment by nullday** [comment]
Hey @rubanraj54 
I'm so sorry, I've figure out that was an issue with my internal component..
I was modifying props indirectly and it led to this issue.

Sorry about that and thanks for great component!
