### ISSUE TITLE
Reset Query button error, Cannot set property 'value' of undefined"

### ISSUE THREAD

**Issue by 2IhsanWp** [rubanraj54/vue-bootstrap4-table#41]
Hi,

i have 2 tables in a different component and routing, let say user and product. in the first reload to user component the button its working fine, but when i change to  another route/product component, the reset button throwing  error Cannot set property 'value' of undefined" i need to refresh the current route to this button work correctly 

im using version 1.1.2
 
![image](https://user-images.githubusercontent.com/47314082/56142884-a3a3d880-5fc9-11e9-8733-167cdb4a0594.png)

**Comment by rubanraj54** [comment]
Hi @2IhsanWp 

This looks strange, I will give a try on my side and check what causes this error.

If you can make a codepen with this issue, then it would be easy for me to debug.

Cheers,
Ruby.

**Comment by hasangok** [comment]
I have same issue, looking forward to hear about updates. Thanks!

**Comment by rubanraj54** [comment]
Hi @2IhsanWp @hasangok 

I've fixed this bug in the develop branch and tomorrow I'll make a new release with a couple of other fixes.

Please update your package tomorrow to avoid this error.

And, if you like this plugin please star this repository. 

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hi @2IhsanWp @hasangok

This issue is fixed in version 1.1.4. So please update your package.

Cheers,
Ruby.
