### ISSUE TITLE
How to add edit/delete button at the end of each row?

### ISSUE THREAD

**Issue by pjsaran** [rubanraj54/vue-bootstrap4-table#43]
How to add edit/delete button at the end of each row? On clicking edit/delete i would like call a function.

**Comment by rubanraj54** [comment]
Hi @pjsaran 

You can use row slots to achieve this.

Also, I've made an example for you here https://codepen.io/rubanraj54/pen/EJepqq .

I hope this codepen will help you. You can find more info about row slot here https://rubanraj54.gitbook.io/vue-bootstrap4-table/rows#row-slot .

Cheers,
Ruby.

**Comment by pjsaran** [comment]
Hi @rubanraj54 

Thanks for the example. It works fine for me now.
