### ISSUE TITLE
Error in callback for watcher "query.filters": "TypeError: Cannot read property 'toString' of null"

### ISSUE THREAD

**Issue by shivanaru** [rubanraj54/vue-bootstrap4-table#49]
If a column has null values, then adding a column filter on that column throws an error: Error in callback for watcher "query.filters": "TypeError: Cannot read property 'toString' of null".

**Comment by rubanraj54** [comment]
Hi @shivanaru ,

Thanks for reporting the issue. I've fixed this issue in develop branch.

Cheers,
Ruby.

**Comment by shivanaru** [comment]
Great! Thanks!
