### ISSUE TITLE
Checkbox rows

### ISSUE THREAD

**Issue by deviilingga** [rubanraj54/vue-bootstrap4-table#5]
when i set on config with checkbox_row: false or removed it, the header of the tables still includes the checkbox. any solution for solve that?

**Comment by rubanraj54** [comment]
Hey @deviilingga. Thanks for reporting the issue.

Actually this bug has been fixed in latest version (1.0.18). Could you please update "vue-bootstrap4-table" package to new version and check?

**Comment by rubanraj54** [comment]
I will close this issue, since it is already fixed in current version. 

If you still facing the issue, pls @deviilingga reopen the issue.
