### ISSUE TITLE
Simple filter of type 'select', close on selection

### ISSUE THREAD

**Issue by soongsta** [rubanraj54/vue-bootstrap4-table#50]
Hi @rubanraj54 

This is a enhancement request.
Would it be possible that after the user chooses a item from the 'select' filter, for the dropdown selection to close.

Right now, it stays open until the user clicks away.

This would apply to the 'multi' select filter as well

Cheers

**Comment by rubanraj54** [comment]
Hi @soongsta 

I've implemented this feature in the develop branch. Soon you will get this feature in next release.

Use can control the dropdown close on selection by enabling the new option **hideDropdownOnSelection** in the filter configuration. By default, it is set to false. And it works for both **single** & **multi** filters.

```javascript
...
{
    label: "First Name",
    name: "name.first_name",
    filter: {
        type: "select",
        placeholder: "Select first name",
        options: [],
        mode:"multi",
        hideDropdownOnSelection: true, //new option here
    }
},
...
```

Cheers,
Ruby.

**Comment by soongsta** [comment]
Awesome
