### ISSUE TITLE
Formatted text in column

### ISSUE THREAD

**Issue by chemeng** [rubanraj54/vue-bootstrap4-table#56]
Hey, what's the best way to show formatted text in a cell? For example let's say that I want to have a bold word so my td string is <strong>Example</strong>. How can I output the formatted text instead of the literal string? I tried using a "display: inline" css attribute in a custom slot but it doesn't seem to do the trick.

Thanks a lot!

**Comment by rubanraj54** [comment]
Hi @chemeng 

You can achieve this using row slots.

Example:

```vue
<div id="app">
  <vue-bootstrap4-table :rows="rows" :columns="columns" :actions="actions" :config="config" @on-download="onDownload" :classes="classes">
        <template slot="email" slot-scope="props">
        <b>
            {{props.cell_value}}
        </b>
      </template>
      <template slot="name_first_name" slot-scope="props">
        <b>
            {{props.cell_value}}
        </b>
      </template>
  </vue-bootstrap4-table>
</div>

```

You can find the working example in this codepen https://codepen.io/rubanraj54/pen/qGPqzB

For more information, visit the documentation page  https://rubanraj54.gitbook.io/vue-bootstrap4-table/rows#row-slot

Cheers,
Ruby.

**Comment by chemeng** [comment]
Thanks for the reply Ruby! I'm actually trying to display dynamic, basically the props.cell_value will be equal to <b>Text</b> and I would like that to be evaluated as html not as string literal. Basically, I have a text editor that saves some text in rich html and would like to display that text within a particular element. Specifying the format explicitly with <b> would not work in that case.

**Comment by rubanraj54** [comment]
Hi @chemeng 

You can user **v-html** render your content as html https://vuejs.org/v2/guide/syntax.html#Raw-HTML.

Example:

```vue
<div id="app">
  <vue-bootstrap4-table :rows="rows" :columns="columns" :actions="actions" :config="config" @on-download="onDownload" :classes="classes">
        <template slot="email" slot-scope="props">
          <span v-html="props.cell_value">
          </span>
        </template>    
        <template slot="name_first_name" slot-scope="props">
          <span v-html="props.cell_value">
          </span>
      </template>
  </vue-bootstrap4-table>
</div>
```

I updated the same codepen example too, please have a look here https://codepen.io/rubanraj54/pen/qGPqzB.

I hope this solves your problem.

Cheers,
Ruby.

**Comment by chemeng** [comment]
Awesome, this does the trick perfectly! I didn't know about v-html but thanks for the tip!
