### ISSUE TITLE
Bug: reset filter fails when global search is not visible

### ISSUE THREAD

**Issue by picakoch** [rubanraj54/vue-bootstrap4-table#61]
Hello,

Firstly, thanks for this amazing component !
Just a minor bug, when the global_search is set to invisible, then the resetQuery function fails here (line 1038 of VueBootstrap4Table.vue)
```
            this.$refs.global_search.value = "";
```
since the ref does not exists if the global search is not visible. Because of the error, other filters are not reset. 

Here is my config : 
```
{
  show_reset_button: true,
  server_mode: true,
  global_search: {
    visibility: false
  }
},
```
I guess a simple test around the line should be do the trick.

Thanks !
Antoine

**Comment by rubanraj54** [comment]
Hey @picakoch ,

Thanks for notifying me.. I will do the test and fix the bug.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
Hey @picakoch 

I fixed the bug in the new release.

Cheers,
Ruby.
