### ISSUE TITLE
Add an localization to the component.

### ISSUE THREAD

**Issue by it-xtech-dev** [rubanraj54/vue-bootstrap4-table#65]
Hello,

Are you planning to add localization features to the component? Localization tokens could be specified as one of the props (lang - for example).

If you have no time for that i could possibly help you.

**Comment by rubanraj54** [comment]
Hi @it-xtech-dev ,

Currently I don't have plans for localization feature, also Nowadays I am spending less time on contributing open source.

I'm is always welcome to accept pull requests and it would be really great if you can add localization feature to this plugin.

Cheers,
Ruby.

**Comment by it-xtech-dev** [comment]
Do you have any requirements how localication should be implemented?

The props idea is ok for you?

**Comment by rubanraj54** [comment]
Hey @it-xtech-dev,

I was thinking about a situation where Localization might be used in this plugin, and there is no place Localization is required since users can override the defaults through slots or props.

So I could say it's not required for this plugin.

Cheers,
Ruby.

**Comment by rubanraj54** [comment]
I will close this issue since there is no response for a long time. But you can re-open the comment anytime.

Cheers,
Ruby,
