### ISSUE TITLE
Readme.md, 12 custom actions buttons, missing ':actions'

### ISSUE THREAD

**Issue by jcerdan** [rubanraj54/vue-bootstrap4-table#69]
Hi,

There's a 

`:actions="actions"`

missing in the `<vue-bootstrap4-table>` tag in the Readme.md (doc) file.

Regards

**Comment by rubanraj54** [comment]
hi @jcerdan ,

Thanks for letting me know, I fixed it in the master.

Cheers,
Ruby.
