### ISSUE TITLE
Sort Order Desc on first click

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [rubanraj54/vue-bootstrap4-table#9]
When i have a table with columns that have no inital sort and i click to sort one of these columns it tries to sort in desc order to begin with.

Now i would expect the first click of sort to order by asc, is this a bug or is there some way i can configure this?

**Comment by rubanraj54** [comment]
Hi @Chris-Pratt-Clystnet, Thanks for reporting an issue.

By default, table tries to do desc sort. 

But, Now I feel it is more sensible that initially table should do the "asc" sort if there is no initial sort provided.

I will fix this by today and let you know.

**Comment by Chris-Pratt-Clystnet** [comment]
@rubanraj54 thanks

**Comment by rubanraj54** [comment]
Hi @Chris-Pratt-Clystnet I fixed this in new version 1.0.23.

Update your package to get the changes.

If you would like to support this plugin, please give this repository a star ⭐
